print("My name is Asadbek.")
print("My name is Emmanuella")
print("Welcome to CS")
print("Whats your favourite colour?")
print("Purple, what about yours?")
print("Mine is blue")
print("What's your favourite food?")
print("Probably ice cream, what about you?")